export { iLinkClient } from "./ilink-client";
export {
  MESSAGE_TYPE_USER,
  MESSAGE_TYPE_BOT,
  MESSAGE_STATE_NEW,
  MESSAGE_STATE_GENERATING,
  MESSAGE_STATE_FINISH,
  WeChatItemType,
  extractTextFromItem,
  iLinkError,
  SessionExpiredError,
  NetworkError,
  RateLimitError,
  iLinkAPIError,
} from "./types";
export type {
  iLinkConfig,
  iLinkBaseInfo,
  iLinkGetUpdatesRequest,
  iLinkGetUpdatesResponse,
  iLinkSendMessageRequest,
  iLinkMessage,
  iLinkSendTypingRequest,
  iLinkGetConfigRequest,
  iLinkGetConfigResponse,
  iLinkGetUploadUrlRequest,
  iLinkGetUploadUrlResponse,
  iLinkQRCodeResponse,
  iLinkQRCodeStatusResponse,
  WeChatMessage,
  WeChatMessageItem,
  WeChatTextItem,
  WeChatImageItem,
  WeChatFileItem,
  WeChatVoiceItem,
  WeChatVideoItem,
} from "./types";